import { RepositoryContext } from "@/lib/repository-context";

export type AssistantSource = { path: string; startLine: number; endLine: number };
export type AssistantReply = { answer: string; sources: AssistantSource[]; actions: string[]; mode: "grounded" | "ai" };

function source(path: string, content?: string): AssistantSource { return { path, startLine: 1, endLine: Math.max(1, (content?.split("\n").length ?? 1)) }; }
function evidence(context: RepositoryContext, predicate: (path: string, content: string) => boolean) {
  return context.files.filter(file => predicate(file.path, file.content ?? "")).slice(0, 6).map(file => source(file.path, file.content));
}
function list(items: string[]) { return items.length ? items.map(item => `- \`${item}\``).join("\n") : "- No repository evidence was retrieved for this area."; }

export function buildGroundedReply(message: string, context: RepositoryContext): AssistantReply {
  const query = message.toLowerCase().trim();
  const baseSources = context.files.filter(file => file.importance === "high").slice(0, 6).map(file => source(file.path, file.content));
  if (/readme|documentation/.test(query)) return { mode: "grounded", actions: ["view-readme", "improve-readme"], sources: [source(context.readme.path, context.readme.content), ...evidence(context, path => /package\.json|\.env\.example|CONTRIBUTING/i.test(path))], answer: `## Summary\nRepoRefine inspected the repository before preparing this documentation view. The current README is at \`${context.readme.path}\`; its generated replacement should be constrained by the detected scripts and environment keys below.\n\n## Facts\n- Package manager: ${context.packageManager ?? "not detected"}\n- Scripts: ${Object.keys(context.scripts).length ? Object.entries(context.scripts).map(([name, command]) => `\`${name}\`: \`${command}\``).join(", ") : "none retrieved"}\n- Environment variables: ${context.environmentVariables.length ? context.environmentVariables.map(key => `\`${key}\``).join(", ") : "none detected"}\n\n## Recommendation\nUse the **Generated README** in the audit view for a repository-specific draft. Add only commands and variables confirmed above.` };
  if (/architecture|structure|explain (this )?repo|repo-summary|summary/.test(query)) return { mode: "grounded", actions: ["view-files", "generate-architecture"], sources: baseSources, answer: `## Summary\n${context.owner}/${context.repository} is indexed from branch \`${context.branch}\` at commit \`${context.commitSha.slice(0, 7)}\`.\n\n## Facts\n- Languages: ${Object.keys(context.languages).join(", ") || "not reported by GitHub"}\n- Framework signals: ${context.frameworks.join(", ") || "none detected"}\n- Entry points:\n${list(context.entryPoints)}\n- CI workflows:\n${list(context.ciCd)}\n\n## Inference\nThe layout suggests the components above are the primary application boundaries; inspect the referenced files before making implementation claims.\n\n## Evidence\n${baseSources.map(item => `- \`${item.path}\``).join("\n")}` };
  if (/issue|priority|plan/.test(query)) return { mode: "grounded", actions: ["view-issues", "create-plan"], sources: [], answer: `## Issue intelligence\nRepoRefine retrieved ${context.issues.length} open issues (pull requests excluded). Priority signals below are transparent: labels containing security, bug, or blocker are elevated; age is shown as context rather than an automatic ranking.\n\n${context.issues.length ? context.issues.map(issue => `### #${issue.number} — ${issue.title}\n- Labels: ${issue.labels.length ? issue.labels.join(", ") : "none"}\n- Age: ${issue.ageDays} days\n- Priority signal: ${/security|bug|blocker/i.test(issue.labels.join(" ")) ? "elevated by explicit labels" : "review impact and dependencies"}`).join("\n\n") : "No open issues were returned by GitHub."}` };
  if (/ci|cd|workflow|actions/.test(query)) return { mode: "grounded", actions: ["generate-ci", "view-workflows"], sources: evidence(context, path => /^\.github\/workflows\/|package\.json$/i.test(path)), answer: `## CI/CD\n\n### Facts\n- Workflows found:\n${list(context.ciCd)}\n- Available package scripts: ${Object.keys(context.scripts).length ? Object.keys(context.scripts).map(script => `\`${script}\``).join(", ") : "none retrieved"}\n- Package manager: ${context.packageManager ?? "not detected"}\n\n### Recommendation\nA generated pipeline must only run commands present in the scripts listed above. Do not add a test stage unless a test script or test framework is detected.` };
  if (/security|vulnerab|secret/.test(query)) return { mode: "grounded", actions: ["view-security"], sources: evidence(context, path => /SECURITY|codeql|dependabot|\.env\.example/i.test(path)), answer: `## Security evidence\n- Security configuration files:\n${list(context.security)}\n- Environment example keys: ${context.environmentVariables.length ? context.environmentVariables.map(key => `\`${key}\``).join(", ") : "none detected"}\n\n## Important\nThis is a configuration review, not a vulnerability finding. RepoRefine does not claim a vulnerability without scanner or GitHub alert evidence.` };
  const requestedPath = context.files.find(file => query.includes(file.path.toLowerCase()));
  const textMatches = evidence(context, (path, content) => path.toLowerCase().includes(query.replace(/^\/find\s*/, "")) || content.toLowerCase().includes(query.replace(/^\/find\s*/, "")));
  const sources = requestedPath ? [source(requestedPath.path, requestedPath.content)] : textMatches.length ? textMatches : baseSources;
  return { mode: "grounded", actions: ["view-files"], sources, answer: `## Grounded response\nI searched the indexed repository context for your request. ${requestedPath ? `The requested file \`${requestedPath.path}\` was retrieved.` : "The most relevant retrieved files are listed as evidence."}\n\n## Evidence\n${sources.map(item => `- \`${item.path}\` (lines ${item.startLine}-${item.endLine})`).join("\n")}\n\n## Next step\nAsk \`/explain <file path>\`, \`/find <query>\`, \`/architecture\`, \`/issues\`, or \`/ci\` to narrow the analysis.` };
}
